logging:
  #日志存储地址
#  file: "logs/config/demo-xx.log"
info:
  name : "入门案例"

server:
  #端口号
  port: 9999
  #项目名，如果不设定，默认是 /
  context-path: /

spring:
  datasource:
    url: jdbc:mysql://192.168.0.14:3306/uyiban-test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 1
    driver-class-name: com.mysql.jdbc.Driver
