spring:
  datasource:
    url: jdbc:mysql://192.168.0.14:3306/uyiban_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 1qazse4
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
    redis:
      cache-null-values: true
  redis:
    redisson:
      config: classpath:redisson/redisson.yml
  logging:
    config: classpath:logback/logback-dev.xml
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

page helper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
